### ISSUE TITLE
Package for pypi and conda forge

### ISSUE THREAD

**Issue by moorepants** [psi4/psi4numpy#107]
It would be helpful for downstream users if this package was available via pypi and conda forge. This would allow users to install the package via commands like:

```
pip install psi4numpy
conda install -c conda-forge psi4numpy
```

**Comment by loriab** [comment]
Thanks for the request. We’re all for packaging and distributing software in general but exempted this repo for two reasons:

* this is a collection of scripts and notebooks rather than a module, so I don’t know what one would want to type next after “import psi4numpy”. 

* packaging would also require distributing psi4 through the same channel. Pip is no-go because it’s too easy to get a broken or inefficient psi4 with pip’s compilation controls. Psi4 is distributed through conda, though through -c psi4 rather than -c conda-forge. The latter would need many more dependencies added to be ready for psi4 before p4n. 

Glad to hear counterarguments.

**Comment by moorepants** [comment]
Good to know. I've had some users request this installed for use in Libretexts. I assumed it was somehow a library. We'll let the users know that they can simply use the content here. Thanks!

**Comment by loriab** [comment]
Interesting! I've referred this to our Psi4Education team in case they have more ideas for integration.
